config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :labels
  resources :publications
    devise_for :users do
      resources  :publications
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
  #Relaciones
  belongs_to :user
  #relacion con labels
  has_and_belongs_to_many :labels
  #relacion con tabla intermedia
  has_many :boards, dependent: :destroy #eliminación en cascada, se elimina la reserva tambien
  has_many :users, through: :boards

  accepts_nested_attributes_for :users

  #relacion photo
  has_one_attached :photo

  #paginación
  paginates_per 4

  #validacion
  validates :title, presence: true
  validates :description, presence: true
  validates :route, presence: true
  validates :price, presence: true
  validates :photo, attached: true, content_type: ['image/png', 'image/jpeg']

  accepts_nested_attributes_for :labels ,
  reject_if: proc { |attr| attr['contact'].blank? },
  allow_destroy: true

  def to_s
      title
      description
      route
      price
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :tengo_permisos?, except: [:index, :show, :new]
  before_action :set_publication, only: %i[ show edit update destroy ]
  
  # GET /publications or /publications.json
  def index
    @publications = Publication.order(:title).page(params[:page])
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
    2.times {@publication.labels.build}
    @publication.users.build
  end

  # GET /publications/1/edit
  def edit
    1.times {@publication.labels.build}
    @publication.users.build
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "La Publicación fue Creada con éxito." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "La Publicación se Actualizó con éxito." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "La Publicación ha sido Eliminada." }
      format.json { head :no_content }
    end
  end

  private    

  
 
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :description, :route, :price, :user_id, :photo, labels_attributes: [:id, :contact, :_destroy])
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_comments.html.erb
<div class="card comments mt-5 mb-5">
  <div class="card-header border-bottom-0 font-weight-bold bg-transparent">Comentarios</div>
  <ul class="list-group list-group-flush">
    <% @publication.boards.each do |comment| %>
      <li class="list-group-item">
        <header class="comment-header"><strong><%= comment.user.email %></strong> escrito <%= distance_of_time_in_words(Time.current, comment.created_at) %> atras</header>
        <div class="comment-body"><%= comment.body %></div>
      </li>
    <% end %>

    <% if @publication.boards.empty? %>
      <li class="list-group-item text-center">Aún no hay comentarios para esta Publicación :(</li>
    <% end %>
  </ul>
</div>

<% if signed_in? %>
  <div class="card bg-light new-comment">
    <div class="card-body">
      <p class="font-weight-bold">Comentario de Publicaciones:</p>
      <%= form_for @publication.boards.build do |f| %>
        <%= f.hidden_field :publication_id, value: @publication.id %>
        <div class="form-group">
          <%= f.text_area :body, rows: 4, class: "form-control" %>
        </div>
        <div class="text-right">
          <%= f.submit "Comentar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="card bg-light mt-5">
    <div class="card-body">
      <p class="card-text text-center lead"><%= link_to "Regístrate", new_user_registration_path %> o <%= link_to "Ingresa", new_user_session_path %> para comentar</p>
    </div>
  </div>
<% end %>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>
      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="row alert alert-secondary border border-info">
      <div class="col-xl-6 col-12">
        <%= form.label :Título, style: "display: block" %>
        <%= form.text_field :title , class:'form-control' %>
      </div>
      <div class="col-xl-6 col-12">
        <%= form.label :Descripción, style: "display: block" %>
        <%= form.text_area :description, class:'form-control'%>
      </div>
      <div class="col-xl-6 col-12">
        <%= form.label :Redes_Sociales, style: "display: block" %>
        <%= form.text_field :route, class:'form-control'%>
      </div>
      <div class="col-xl-6 col-12">
        <%= form.label :Foto, style: "display: block" %>
        <%= form.file_field :photo ,class:'form-control' %>  
      </div>
      <div class="col-xl-6 col-12">
        <%= form.label :Precio, style: "display: block" %>
        <%= form.text_field :price, class:'form-control'%>
      </div>
      <div  class="col-xl-4 col-12">
          <%= form.fields_for :labels do | etiqueta | %>
            <div class="labels_fields">
                <div class="fields">
                  <%= etiqueta.label :contact, "Etiqueta" %><br>
                  <%= etiqueta.text_field :contact ,class:'form-control' %>
                  <%= etiqueta.check_box :_destroy %>
                  <%= etiqueta.label :_destroy, "Borrar",data: { confirm: 'Are you sure?' } %>
                </div>
            </div>
          <% end %>
        </div>
      <div>
      <div  class="col-xl-4 col-12">
      <% @varo = current_user.try(:id) %>
      <%= form.fields_for(:users) do |entity_form| %>
          <%= entity_form.hidden_field :user_id, value: @varo %>         
      <% end %>
      </div>
      
      <div>
          <% @var = current_user.try(:id) %>
          <% form.label :user_id, style: "display: block" %>
          <%= form.hidden_field :user_id, value: @var %>         
      </div>
      <div class="col-xl-6 col-4">
          <br/>
          <%= form.submit  class:'bi bi-pencil-square btn btn-primary'%>
      </div>
  </div>
</div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <strong>Título:</strong>
    <%= publication.title %>
  </p>
  <p>
    <strong>Descripción:</strong>
    <%= publication.description %>
  </p>
  <p>
    <strong>Redes Sociales:</strong>
    <%= publication.route %>
  </p>
  <p>
    <strong>Precio:</strong>
    <%= publication.price %>
  </p>
  <p class="visually-hidden">
    <strong>Usuario:</strong>
    <%= publication.user_id %>
  </p>
</div>

app/views/publications/edit.html.erb
<h1>Editar publicación</h1>

<%= render "form", publication: @publication %>

<br>

<div class="row">
  <div class="col-xl-3">
    <%= link_to " Mostrar Publicación", @publication , class:'bi bi-eye-fill btn btn-outline-info' %>
  </div>
  <div class="col-xl-3">
    <%= link_to "Volver a Publicación", publications_path, class:'bi bi-house-door btn btn-outline-primary'%>
  </div>
</div>

app/views/publications/index.html.erb
<% if current_user %>
<div class="d-grid gap-2 d-md-flex justify-content-md-end border border-primary rounded">
   <p>Hola <b><%= current_user.email %>!</b>
   tu eres a <b>[<%= current_user.rol  %>]</b>
   <% if current_user.admin? %>
       son <%= User.count %> usuarios en el sistema
   <% end %>
   usuario autentificado</p>
   <%= link_to " Cerrar Sesión", destroy_user_session_path,'data-turbo-method': :delete,  class:'bi bi-bag-x-fill btn btn-danger' %>
</div>
<% else %>
   
<div class="d-grid gap-2 d-md-flex justify-content-md-end border border-primary rounded">
  <p class="col-3"><b>No estas Autentificado</b></p>
  <%=link_to " Registrarse", new_user_registration_path, class:'bi bi-newspaper btn btn-primary  me-md-2 col-3 rounded-pill' %>
  <%=link_to " Ingresar", new_user_session_path, class:'bi bi-hand-index-thumb btn btn-info  col-3 rounded-pill' %>
<% end %>
</div>
<br/>
<div>
  <% if user_signed_in? %>
    <%= link_to "Nueva Publicación", new_publication_path, class:'bi bi-file-earmark-plus btn btn-success col-3' %>  
  <% end %>
</div>
<div  id="publications" class="row container-fluid">
    <h1>Publicaciones</h1>
    <%= paginate @publications %>
    <% @publications.each do |publication| %>
      <div class="container-fluid card text-dark bg-light mb-3 c " style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-5">
                <p class="card-text"><small class="text-muted"><%= link_to "Tablero de Publicación", publication, class:'bi bi-eye-fill btn btn-primary' %></small></p>
                <%= image_tag publication.photo, width:200,class:'img-fluid rounded-circle border border-1 border border-secondary' if publication.photo.attached? %>
            </div>
            <div class="col-md-7">
              <div class="card-body">
                <p class="card-text"><%= render publication %></p>
                <p class="card-text">
                  <h5>Etiquetas</h5>
                  <% if publication.labels.any? %>
                    <ul>
                      <% publication.labels.each do |etiquetas| %>
                         <li class="btn btn-outline-info"><%= link_to etiquetas, etiquetas %></li>
                      <% end %>
                    </ul>
                    <% else %>
                    <p>no hay etiquetas</p>
                  <% end %>
                </p>
                <br>                    
              </div>              
            </div>
          </div>
      </div>
    <% end %>
    <%= paginate @publications %>
</div>

app/views/publications/new.html.erb
<h1>Nueva publicacion</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Volver a Publicación", publications_path , class:'bi bi-house-door btn btn-outline-primary'%>
</div>

app/views/publications/show.html.erb
<div class="card container-fluid mb-3 border border-info card text-dark bg-light mb-3" style="max-width: 1200px;">  
  <div class="row col-xl-12 g-0">
    <div class="col-md-4 col-xl-4">
      <br/><br/>
      <%= image_tag @publication.photo,class:'img-fluid rounded-circle border border-1 border border-secondary',width:200  if @publication.photo.attached? %>
    </div>
    <div class="col-md-8 col-xl-8">
      <div class="card-body">
        <p class="card-text"> <%= render @publication %></p>
        <p class="card-text"><small class="text-muted">
            <h3>Etiquetas</h3>
            <% if @publication.labels.any? %>
              <ul>
                <% @publication.labels.each do |etiquetas| %>
                  <li class="btn btn-outline-info"><%= link_to etiquetas, etiquetas %></li>
                <% end %>
              </ul>
            <% else %>
                <p>no hay etiquetas</p>
            <% end %>
          </small>
        </p>
      
      </div>
    </div>
  </div>
  <div class="col-4 col-xl-4">
     <%= link_to "Volver al Inicio", publications_path, class:'bi bi-house-door btn btn-primary btn-sm'%>
  </div>
  <!--Si esta logeado puede ver estos botones -->
  <% if user_signed_in?  %>
  <div class="row container-fluid alert alert-primary border border-info">
    <div class="col-4 col-xl-4">
      <%= link_to "Editar Publicación", edit_publication_path(@publication), class:'bi bi-pencil-square btn btn-info btn-sm'%> 
    </div>
    <div class="col-4 col-xl-4">
      <%= button_to "Eliminar publicación", @publication, method: :delete, class:'bi bi-trash3-fill btn btn-danger btn-sm',data: { confirm: 'Are you sure?' }%>     
    </div>
    <div class="container">
      <%= render 'publications/comments' %>
    </div>
  <% end %>
      <br/>
  </div>
</div>