config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :labels
  resources :publications
    devise_for :users do
      resources  :publications
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/label.rb
class Label < ApplicationRecord

  #relaciones
  has_and_belongs_to_many :publications
  
  #validaciones
  validates :contact, presence: true
  def to_s
    contact
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to label_url(@label), notice: "Label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to label_url(@label), notice: "Label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:contact, :publication_id)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label :publication_id, style: "display: block" %>
    <%= form.text_field :publication_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/_label.html.erb
<div id="<%= dom_id label %>">
  <p>
    <strong>Contact:</strong>
    <%= label.contact %>
  </p>

  <p>
    <strong>Publication:</strong>
    <%= label.publication_id %>
  </p>

</div>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render "form", label: @label %>

<br>

<div>
  <%= link_to "Show this label", @label %> |
  <%= link_to "Back to labels", labels_path %>
</div>

app/views/labels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Labels</h1>

<div id="labels">
  <% @labels.each do |label| %>
    <%= render label %>
    <p>
      <%= link_to "Show this label", label %>
    </p>
  <% end %>
</div>

<%= link_to "New label", new_label_path %>

app/views/labels/new.html.erb
<h1>New label</h1>

<%= render "form", label: @label %>

<br>

<div>
  <%= link_to "Back to labels", labels_path %>
</div>

app/views/labels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @label %>

<div>
  <%= link_to "Edit this label", edit_label_path(@label) %> |
  <%= link_to "Back to labels", labels_path %>

  <%= button_to "Destroy this label", @label, method: :delete %>
</div>