config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :labels
  resources :publications
    devise_for :users do
      resources  :publications
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :publication
  belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :authenticate_user!
    def index 
      @boards = Board.all
    end
    def show
    end

    def new
      @board = Board.new
    end

    def create
      publication = Publication.find(params[:board][:publication_id])
      board = publication.boards.build(board_params)
      board.user = current_user
    
      if board.save
        redirect_to board.publication
      end
    end

    def update
      publication = Publication.find(params[:board][:publication_id])
      board = publication.boards.build(board_params)
      board.user = current_user
    
      if board.update
        redirect_to board.publication
      end
    end

    def destroy
      @board.destroy

      respond_to do |format|
        format.html { redirect_to labels_url, notice: "Board was successfully destroyed." }
        format.json { head :no_content }
      end
    end  
    
    private
      def board_params
        params.require(:board).permit(:body)
      end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div id="<%= dom_id board %>">  

  <p>
    <strong>Publication:</strong>
    <%= board.publication_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= board.user_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= board.body %>
  </p>

</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div> 
    <%= form.label :publication_id, style: "display: block" %>
    <%= form.text_field :publication_id %>
  </div>

  <div>
  <% @varo = current_user.try(:id) %>
      <%= form.fields_for(:users) do |entity_form| %>
          <%= entity_form.hidden_field :user_id, value: @varo %>
  <% end %>
  </div>

   <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Boards</h1>

<div id="boards">
  <% @boards.each do |board| %>
    <%= render board %>
    <p>
      <%= link_to "Show this board", board %>
    </p>
  <% end %>
</div>

<%= link_to "New board", new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board %>

<div>
  <%= link_to "Edit this board", edit_board_path(@board) %> |
  <%= link_to "Back to boards", boards_path %>

  <%= button_to "Destroy this board", @board, method: :delete %>
</div>